final int WINDOW_WIDTH = 1800;
final int WINDOW_HEIGHT = 1200;
final color BACKGROUND_COLOR = color(200, 230, 255);
final color TEXT_COLOR = color(0);
final color TITLE_COLOR = color(10, 10, 10, 150);
final color BUTTON_COLOR = color(144, 238, 144);
final color HIGHLIGHT_COLOR = color(200, 200, 0, 150);
final int CHARACTER_WIDTH = 4;
final int SCROLL_SPEED = 10;
final int TABLE_TOP_BORDER = 20;
final int TABLE_LEFT_BORDER = 20;
final int BLINK_INTERVAL = 30;
final int COLUMN_SPACE = 45;
final int ROW_HEIGHT = 20;
final int MIN_BAR_WIDTH = 500;
final int MAX_BAR_WIDTH = 2000;
final int MIN_BAR_HEIGHT = 300;
final int MAX_BAR_HEIGHT = 1000;
final int FLIGHTS_PER_PAGE = 50;
final String MAIN_FILE_NAME = "cleanFlights2k.csv";
final String BIG_FONT = "AgencyFB-Bold-20.vlw";
final String MEDIUM_FONT = "AgencyFB-Bold-15.vlw";
final String SMALL_FONT = "AgencyFB-Bold-10.vlw";
final int anchorageX = 190;
final int anchorageY = 730;
final int albanyX = 860;
final int albanyY = 250;
final int atlantaX = 690;
final int atlantaY = 450;
final int bostonX = 920;
final int bostonY = 235;
final int albuquerqueX = 290;
final int albuquerqueY = 450;
final int austinX = 510;
final int austinY = 520;
final int baltimoreX = 890;
final int baltimoreY = 255;
final int bozemanX = 270;
final int bozemanY = 185;
final int laX = 95;
final int laY = 400;
final int dallasX = 470;
final int dallasY = 415;
final int denverX = 310;
final int denverY = 295;
final int charlotteX = 860;
final int charlotteY = 340;
final int chicagoX = 610;
final int chicagoY = 235;
final int honoluluX = 780;
final int honoluluY = 695;
final int nyX = 910;
final int nyY = 270;
final int seattleX = 75;
final int seattleY = 150;
final int nashvilleX ;
final int nashvilleY ;
final int washingtonX ;
final int washingtonY ;
final int detroitX ;
final int detroitY ;
final int newarkX ;
final int newarkY ;
final int fortLauderdaleX;
final int fortLaurderdaleY;
final int houstonX;
final int houstonY;
final int juneauX;
final int juneauY;
final int vegasX;
final int vegasY;
final int orlandoX;
final int orlandoY;
final int portlandX;
final int portlandY;
final int sanFranciscoX;
final int sanFranciscoY;
final int kahuluiX;
final int kahuluiY;
final int sanJuanX;
final int sanJuanY;
final int ketchikanX;
final int ketchikanY;
final int pheonixX;
final int pheonixY;
